# Generated by Django 4.0.6 on 2022-07-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableau',
            name='photo',
            field=models.ImageField(upload_to='image'),
        ),
    ]
