# Generated by Django 4.0.6 on 2022-07-21 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_tableau_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableau',
            name='photo',
            field=models.ImageField(upload_to='blog/static/images/'),
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personne', models.CharField(help_text='Nom de la personne du commentaire', max_length=50)),
                ('tableau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.tableau')),
            ],
        ),
    ]
