# Generated by Django 4.0.6 on 2022-07-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_commentaire_date_publication_commentaire_texte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableau',
            name='affichage',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tableau',
            name='photo',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
