# Generated by Django 4.0.6 on 2022-08-08 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_tableau_affichage_alter_tableau_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='personne',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='peintre',
            name='description_peintre',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='tableau',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='tableau',
            name='largeur',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tableau',
            name='longueur',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tableau',
            name='nom_tableau',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tableau',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tableau',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.type'),
        ),
    ]
