# Generated by Django 4.0.6 on 2022-08-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_type_alter_commentaire_personne_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableau',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
