# Generated by Django 4.0.6 on 2022-08-08 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_tableau_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableau',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.type'),
        ),
    ]
